DROP TABLE IF EXISTS `RF_ReadForeverUser`;
CREATE TABLE RF_ReadForeverUser (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(60) NOT NULL,
	apikey VARCHAR(60) NOT NULL
);

DROP TABLE IF EXISTS `RF_ReadForeverListData`;
CREATE TABLE RF_ReadForeverListData (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userid INT(11) NOT NULL,
	topicname VARCHAR(255),
	FOREIGN KEY (userid) REFERENCES RF_ReadForeverUser(id)
);
